import random

def random_prompt():
    prompts = [
        "What made you smile today?",
        "Describe your favorite moment this week.",
        "What's your biggest goal for the year?",
        "💭 What's a random shower thought you had today?",
        "🧠 Share one weird fact you know that sounds fake but is true",
        "📚 Recommend one book that changed your perspective on life.",
        "🎧 What song are you looping right now?",
        "🎮 What game are you playing right now?",
        "🥲 What’s something that made you cry (good or bad) recently?",
        "🧳 If you could teleport anywhere right now, where would you go?",
        "⏳ What's one moment you wish you could relive forever?",
        "🔮 What’s a prediction you have for the next 10 years?",
        "🧃 What's your favorite comfort snack?",
        "💬 What’s a quote that lives rent-free in your head?",
        "🌃 Night owl or early bird—and why?",
        "🔥 What hill are you willing to die on (no matter how silly)?",
        "💡 What’s one idea that could change the world?",
        "👽 Aliens visit Earth and ask you to explain the internet. What do you say?",
        "⌛ If you could pause time, what would you do?",
        "📸 What’s the last photo you took and why?",
        "🐍 If animals could talk, which one would be the sassiest?",
        "🕹️ What was your favorite childhood video game?",
        "👟 What’s a trend you wish would come back?",
        "🧩 What’s something small that gives you big joy?",
        "🧛‍♂️ Vampire or Werewolf—you have to choose!",
        "🐶 Dog person, cat person, or chaos gremlin?",
       " 🏖️ Beach day or mountain hike?",
       " 🤖 What would your personal AI assistant be like?",
       " 🧙 If you could master one magical spell, what would it be?",
        "🐉 Name a fantasy creature you’d want as a pet.",
        "📱 What’s an app you use way too much?",
        "🕵️‍♀️ What's your most used emoji and what does it say about you?",
        "🍕 Pineapple on pizza: yes or no?",
        "🚀 First thing you'd do if you landed on Mars?",
        "💬 Describe your mood right now in 3 emojis.",
        "🧠 One thing you wish schools taught?",
        "🎉 Best birthday memory ever?",
        "🎮 If life were a video game, what would be your special power?",
        "🧼 What's your weirdest habit?",
        "🗺️ If your life was a movie, what would it be called?",
        "☕ What’s your go-to coffee/tea order?",
        "🎯 What’s one goal you’re silently working toward?",
        "🌈 What’s your favorite color",
        "🎵 What’s your favorite song?",
        "🕊️ Write your own tweet that would go viral.",
        # Add more prompts
    ]
    return random.choice(prompts)

